version: "2"
linters:
  settings:
    depguard:
      rules:
        main:
          list-mode: lax
          files:
            - $all
  enable:
    - bodyclose
    - contextcheck
    - depguard
    - durationcheck
    - dupl
    - errchkjson
    - errname
    - exhaustive
    - govet
    - makezero
    - misspell
    - nakedret
    - nilerr
    - nilnil
    - noctx
    - prealloc
    - revive
    # - rowserrcheck
    - thelper
    - tparallel
    - unconvert
    - unparam
    # - wastedassign
    - whitespace
