version: 2
project_name: aws-vault

builds:
  - binary: aws-vault
    targets:
      - linux_amd64
      - windows_amd64
      - darwin_amd64
      - darwin_arm64
    env:
      - GOTELEMETRY="off"
    flags:
      - -v
    ldflags:
      - -s -w -X main.Version={{.Version}}
